name: Deploy Test

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    environment: TEST_ENV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV }}" > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env.build file from .env
        run: grep '^NEXT_PUBLIC_' .env > .env.build

      - name: Export NEXT_PUBLIC_* variables as build args
        id: export-public-envs
        run: |
          # Extract NEXT_PUBLIC_* lines from .env
          export BUILD_ARGS=$(grep '^NEXT_PUBLIC_' .env | sed 's/^/--build-arg /' | tr '\n' ' ')
          echo "BUILD_ARGS=$BUILD_ARGS" >> $GITHUB_ENV

      - name: Build Docker image with dynamic NEXT_PUBLIC_* args
        run: docker build ${{ env.BUILD_ARGS }} -t reborn-backoffice .

      - name: Save Docker image to archive
        run: docker save reborn-backoffice -o image.tar

      - name: Fix permissions for image.tar
        run: chmod +r image.tar

      - name: Copy image + .env to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "image.tar,.env"
          target: "/home/${{ secrets.SSH_USER }}/deploy"

      - name: SSH and run container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/deploy
            docker load -i image.tar
            docker stop reborn-backoffice || true && docker rm reborn-backoffice || true
            docker run -d --name reborn-backoffice \
              --env-file .env \
              -p 3001:3000 \
              reborn-backoffice